[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
maxi_auction = "AuYwiNyd1y3cUchTzrFsML5KasUgYWYHvMncxEBCVWhX"

[programs.localnet]
maxi_auction = "AuYwiNyd1y3cUchTzrFsML5KasUgYWYHvMncxEBCVWhX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://mainnet.helius-rpc.com/?api-key=bfd713ef-c9a7-404f-804c-e682c2bd0d3b"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
